### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by buzz-js** [strapi/strapi-starter-nuxt-e-commerce#3]
Live demo it does not work :(

![screencapture-strapi-starter-nuxt-e-commerce-ten-vercel-app-2020-10-02-12_00_25](https://user-images.githubusercontent.com/63687573/94911776-ebad0880-04a6-11eb-9c0d-727ef92ef5a4.png)

**Comment by remidej** [comment]
Nice catch! I think we entered the wrong link as the repo's website. Can you check again?

**Comment by buzz-js** [comment]
> Nice catch! I think we entered the wrong link as the repo's website. Can you check again?

Now it works correctly!
